lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TeacherWeb.Plugs.Veil.UserId)
    plug(TeacherWeb.Plugs.Veil.User)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TeacherWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", AlbumController, :index)
    resources("/albums", AlbumController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", TeacherWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/veil", TeacherWeb.Veil do
    pipe_through(:browser)

    post("/users", UserController, :create)

    get("/users/new", UserController, :new)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)
  end

  # Add your routes that require authentication in this block.
  # Alternatively, you can use the default block and authenticate in the controllers.
  # See the Veil README for more.
  scope "/", TeacherWeb do
    pipe_through([:browser, TeacherWeb.Plugs.Veil.Authenticate])
  end
end

lib/teacher_web/views/layout_view.ex
defmodule TeacherWeb.LayoutView do
  use TeacherWeb, :view
end

lib/teacher_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Teacher!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div class="pull-right">
          <%= if assigns[:veil_user_id] do %>
            <span>Signed in as <%= @veil_user.email %></span>
            <%= link "Sign out", to: session_path(@conn, :delete, @session_unique_id) %>
          <% else %>
            <%= link "Sign in", to: user_path(@conn, :new) %>
          <% end %>
          |
          <%= link "Home", to: album_path(@conn, :index) %>
        </div>
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>